[profile.default]
src = "contracts/src"
out = "contracts/out"
test = "contracts/test"
script = "contracts/script"
libs = ["contracts/lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 10
via_ir = true

remappings = [
  "@openzeppelin/=contracts/lib/openzeppelin-contracts/",
  "forge-std/=contracts/lib/forge-std/src/",
]
